// <auto-generated />
namespace MSTSolution.LivrosApi.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriacaoTabelaLivros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriacaoTabelaLivros));
        
        string IMigrationMetadata.Id
        {
            get { return "202010101831100_CriacaoTabelaLivros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
